use_frameworks!

platform :ios, '11.4'

target 'YAPPakistan_Example' do
  pod 'YAPPakistan', :path => '../'
  pod 'YAPCore', :path => '../YAPCore'
  pod 'YAPComponents', :path => '../YAPComponents'

  target 'YAPPakistan_Tests' do
    inherit! :search_paths

    
  end
end
