use_frameworks!

platform :ios, '11.4'

install! 'cocoapods', :deterministic_uuids => false

source 'https://bitbucket.org/yap-technology/cardscanner-b2b.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'YAPPakistan_Example' do
  pod 'YAPPakistan', :path => '../'
  pod 'YAPCore', :path => '../YAPCore'
  pod 'YAPComponents', :path => '../YAPComponents'

  #MARK: Reactive
  pod 'RxCocoa', '~> 6.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'RxGesture', '~> 4.0'
  pod 'RxOptional', '~> 5.0'
  pod 'RxSwift', '~> 6.0'
  pod 'RxSwiftExt', '~> 6.0'
  pod 'RxTheme', '~> 5.0'

  #MARK: Utilities
  pod 'PhoneNumberKit', '~> 3.0'

  target 'YAPPakistan_Tests' do
    inherit! :search_paths

    
  end
end
