use_frameworks!

platform :ios, '11.4'

install! 'cocoapods', :deterministic_uuids => false

source 'https://bitbucket.org/yap-technology/cardscanner-ios.git'
source 'https://github.com/CocoaPods/Specs.git'

def app_analytics_pods
  pod 'Leanplum-iOS-SDK', '3.2.1'
  pod 'Adjust', '~> 4.29.2'
  pod 'FBSDKCoreKit', '12.3.2'
  pod 'Firebase/Analytics'
end

target 'YAPPakistan_Example' do
  app_analytics_pods
  pod 'YAPPakistan', :path => '../'
  pod 'YAPCore', :path => '../YAPCore'
  pod 'YAPComponents', :path => '../YAPComponents'

#  #MARK: Reactive
#  pod 'RxCocoa', '~> 6.0'
#  pod 'RxDataSources', '~> 5.0'
#  pod 'RxGesture', '~> 4.0'
#  pod 'RxOptional', '~> 5.0'
#  pod 'RxSwift', '~> 6.0'
#  pod 'RxSwiftExt', '~> 6.0'
#  pod 'RxTheme', '~> 5.0'
#
#  #MARK: Utilities
#  pod 'PhoneNumberKit', '~> 3.0'
#  pod 'MXParallaxHeader'

  target 'YAPPakistan_Tests' do
    inherit! :search_paths

    
  end
end
