platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://bitbucket.org/mb28/privatetrunk.git'
source 'https://github.com/LivePersonInc/iOSPodSpecs.git'

target 'Demo' do
  use_modular_headers!

  pod 'YAPPakistan', :path => '../YAPPakistan'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
end
